# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20190102_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='pagrindineNuotrauka',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='summary',
            new_name='pavadinimas',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='kaina',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pagaminimoMenuo',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pagaminimoMetai',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='skelbimasSukurtas',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
