# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190102_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='duruSkaicius',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='kebuloTypas',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='komentarai',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='kuroTypas',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='pavaruDeze',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='ratlankiuSkersmuo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='rida',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='spalva',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='techApziura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vairoPadetis',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='variklis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pagaminimoMenuo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pagaminimoMetai',
            field=models.IntegerField(),
        ),
    ]
