# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20190102_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='duruSkaicius',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='kaina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='kebuloTypas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='komentarai',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='kuroTypas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='pagaminimoMenuo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pagaminimoMetai',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pavadinimas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='pavaruDeze',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='ratlankiuSkersmuo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rida',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='spalva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='techApziura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='vairoPadetis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='variklis',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
