# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20190102_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='prekyboje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year_in_school',
            field=models.CharField(choices=[('Parduodama', 'Parduodama'), ('Parduota', 'Parduota'), ('Procesas', 'Klausti Susisiekus')], default='Parduodama', max_length=10),
        ),
    ]
