# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20190102_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year_in_school',
        ),
        migrations.AlterField(
            model_name='car',
            name='kuroTypas',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas'), ('BenzinasDujos', 'Benzinas / Dujos')], default='Benzinas', max_length=25, verbose_name='Prekyboje?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pavaruDeze',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas'), ('BenzinasDujos', 'Benzinas / Dujos')], default='Automatas', max_length=25, verbose_name='Prekyboje?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='prekyboje',
            field=models.CharField(choices=[('Parduodama', 'Parduodama'), ('Parduota', 'Parduota'), ('Procesas', 'Kita (susisiekite)')], default='Parduodama', max_length=10, verbose_name='Prekyboje?'),
        ),
    ]
