# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20190102_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kuroTypas',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas'), ('BenzinasDujos', 'Benzinas / Dujos')], default='Benzinas', max_length=25, verbose_name='Kuro Tipas'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pavaruDeze',
            field=models.CharField(choices=[('Automatas', 'Automatas'), ('Mechanine', 'Mechaninė')], default='Automatas', max_length=25, verbose_name='Pavarų dėžė'),
        ),
    ]
