# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20190102_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kebuloTypas',
            field=models.CharField(choices=[('Sedanas', 'Sedanas'), ('Hečbekas', 'Hečbekas'), ('Universalas', 'Universalas'), ('Vienatūris', 'Vienatūris'), ('Keleiviniai Mikroautobusai', 'Keleiviniai mikroautobusai'), ('Limuzinas', 'Limuzinas'), ('Visureigis', 'Visureigis'), ('Kupė', 'Kupė (Coupe)'), ('Kabrioletas', 'Kabrioletas'), ('Kita', 'Kita')], default='Sedanas', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='kuroTypas',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas'), ('BenzinasDujos', 'Benzinas / Dujos')], default='Benzinas', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='pavaruDeze',
            field=models.CharField(choices=[('Automatas', 'Automatinė'), ('Mechanine', 'Mechaninė')], default='Automatinė', max_length=25),
        ),
        migrations.AlterField(
            model_name='car',
            name='vairoPadetis',
            field=models.CharField(choices=[('Kairėje', 'Kairėje'), ('Dešinėje', 'Dešinėje')], default='Kairėje', max_length=25),
        ),
    ]
