# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20190102_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masinosMarke', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Mašinos Detalės',
            },
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='CarDetails',
        ),
        migrations.AlterModelOptions(
            name='cardetails',
            options={'verbose_name_plural': 'Mašinos Detalės'},
        ),
    ]
