# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20190102_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmake',
            options={'verbose_name_plural': 'Mašinos Markė'},
        ),
        migrations.AddField(
            model_name='cardetails',
            name='masinosTipas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.CarMake'),
            preserve_default=False,
        ),
    ]
