# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_cardetails_masinostipas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetails',
            options={'verbose_name_plural': 'Mašinos Aprašimas'},
        ),
        migrations.AddField(
            model_name='cardetails',
            name='masinosTipas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
