# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20190102_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='masinosTipas',
        ),
    ]
