# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20190102_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masinosMarke', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Mašinos Markė',
            },
        ),
        migrations.AddField(
            model_name='cardetails',
            name='masinosTIPAS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.CarMake'),
            preserve_default=False,
        ),
    ]
