# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20190102_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarMake',
            new_name='CarMake2',
        ),
    ]
