# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20190102_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmake2',
            old_name='masinosMarke',
            new_name='masinosMarke222',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='masinosTIPAS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.CarMake2'),
        ),
    ]
