# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20190102_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='masinosTIPAS',
        ),
        migrations.DeleteModel(
            name='CarMake2',
        ),
    ]
