# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20190102_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='kad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
