# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_cardetails_kad22'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='kad223',
            field=models.TextField(blank=True, null=True),
        ),
    ]
