# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20190102_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='kebuloTypas',
            new_name='kebuloTipas',
        ),
        migrations.RenameField(
            model_name='cardetails',
            old_name='kuroTypas',
            new_name='kuroTipas',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='pagaminimoMenuo',
            field=models.CharField(choices=[('', ''), ('-01', '01'), ('-02', '02'), ('-03', '03')], default='', max_length=25),
        ),
    ]
