# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_auto_20190104_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='pagrindineNuotrauka',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='nuotrauka',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
