# Generated by Django 2.1.5 on 2019-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20190104_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='nuotrauka',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
