# Generated by Django 2.1.5 on 2019-01-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_auto_20190105_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/'),
        ),
    ]
