# Generated by Django 2.1.5 on 2019-01-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_auto_20190106_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_image', models.ImageField(blank=True, upload_to='car_images/')),
                ('image_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_images', to='cars.CarDetails')),
            ],
        ),
    ]
