# Generated by Django 2.1.5 on 2019-01-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_carimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetails',
            options={'verbose_name_plural': 'Automobilio Aprašimas'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name_plural': 'Automobilio Nuotraukos'},
        ),
    ]
