# Generated by Django 2.1.5 on 2019-01-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_auto_20190115_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car_images_name', to='cars.CarDetails'),
        ),
    ]
