# Generated by Django 2.1.5 on 2019-01-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_auto_20190115_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image_file',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
