# Generated by Django 2.1.5 on 2019-01-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_auto_20190115_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={},
        ),
    ]
