# Generated by Django 2.1.5 on 2019-01-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0040_auto_20190115_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name_plural': 'Automobilio Nuotraukos'},
        ),
        migrations.AddField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(max_length=25, null=True, verbose_name='PapildomasTekstas'),
        ),
    ]
