# Generated by Django 2.1.5 on 2019-01-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0041_auto_20190116_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(max_length=200, null=True, verbose_name='PapildomasTekstas'),
        ),
    ]
