# Generated by Django 2.1.5 on 2019-01-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0042_auto_20190116_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='ratlankiuSkersmuo',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='techApziura',
        ),
        migrations.AddField(
            model_name='cardetails',
            name='defektai',
            field=models.CharField(default='Nėra', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='registracijosSalis',
            field=models.CharField(default='Nėra', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='varantisRatai',
            field=models.CharField(default='Priekiniai', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='duruSkaicius',
            field=models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5'), ('7', '7'), ('Kita', 'Kita')], default='4/5', max_length=10, verbose_name='DuruSkaicius'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='prekyboje',
            field=models.CharField(choices=[('Parduodama', 'Parduodama'), ('Parduota', 'Parduota'), ('Rezervuota', 'Rezervuota'), ('Procesas', 'Kita (susisiekite)')], default='Parduodama', max_length=10, verbose_name='Prekyboje?'),
        ),
    ]
