# Generated by Django 2.1 on 2019-02-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_auto_20190117_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='pavaruDeze',
            field=models.CharField(choices=[('Automatas', 'Automatinė'), ('Mechaninė', 'Mechaninė')], default='Automatinė', max_length=25),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(choices=[('Priekis', 'Priekis'), ('Galas', 'Galas'), ('Šonas', 'Šonas'), ('Variklis', 'Variklis'), ('Vidus', 'Vidus'), ('Bagažinė', 'Bagažinė'), ('Kita', 'Kita')], default='Kita', max_length=200, null=True, verbose_name='PapildomasTekstas'),
        ),
    ]
