# Generated by Django 2.1 on 2019-02-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0044_auto_20190223_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=models.ImageField(upload_to='car_images/', verbose_name='PasirinktiNuotrauka'),
        ),
    ]
