# Generated by Django 2.1 on 2019-02-23 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0047_auto_20190223_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='car_images/', verbose_name='PasirinktiNuotrauka'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='selected_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_car_name', to='cars.CarDetails', verbose_name='PasirinktiAutomobili'),
        ),
    ]
