# Generated by Django 2.1 on 2019-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0049_auto_20190223_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, default='/car_images/default.png', upload_to='car_images/', verbose_name='PragrindineNuotrauka'),
        ),
    ]
