# Generated by Django 2.1.5 on 2019-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0050_auto_20190223_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, default='/car_images/default.png', upload_to='', verbose_name='PragrindineNuotrauka'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='PasirinktiNuotrauka'),
        ),
    ]
