# Generated by Django 2.1.5 on 2019-02-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0051_auto_20190225_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='image',
            field=models.ImageField(blank=True, default='/car_images/default.png', upload_to='', verbose_name='Pragrindine_Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='pavaruDeze',
            field=models.CharField(choices=[('Automatas', 'Automatinė'), ('Mechanine', 'Mechaninė')], default='Automatinė', max_length=25),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='alt_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Papildomas_Tekstas'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='car_images/', verbose_name='Pasirinkti_Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='selected_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_car_name', to='cars.CarDetails', verbose_name='Pasirinkti_Automobili'),
        ),
    ]
