# Generated by Django 2.1.5 on 2019-03-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0052_auto_20190225_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='selected_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_car_name', to='cars.CarDetails', verbose_name='Pasirinkti_Automobili'),
        ),
    ]
