# Generated by Django 2.1.5 on 2019-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0053_auto_20190303_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Markė',
            },
        ),
    ]
