# Generated by Django 2.1.5 on 2019-03-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0055_cardetails_automobilio_marke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='automobilio_marke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='automobilio_marke_name', to='cars.CarMake', verbose_name='Automobilio Markė'),
        ),
    ]
