# Generated by Django 2.1.5 on 2019-03-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0056_auto_20190303_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='car_make',
            field=models.CharField(blank=True, max_length=200, verbose_name='Automobilio Markė'),
        ),
    ]
