# Generated by Django 2.1.5 on 2019-03-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0060_auto_20190307_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='prekyboje',
            field=models.CharField(choices=[('Parduodama', 'Parduodama'), ('Parduota', 'Parduota'), ('Rezervuota', 'Rezervuota'), ('Kita', 'Kita (Nematoma)')], default='Parduodama', max_length=10, verbose_name='Prekyboje?'),
        ),
    ]
