# Generated by Django 2.1.5 on 2019-03-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0061_auto_20190307_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='kuroTipas',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas'), ('BenzinasDujos', 'Benzinas / Dujos'), ('BenzinasElektra', 'Benzinas / Elektra'), ('Elektra', 'Elektra')], default='Benzinas', max_length=25),
        ),
    ]
