# Generated by Django 2.1.5 on 2019-08-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0062_auto_20190316_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='duruSkaicius',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='registracijosSalis',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='vairoPadetis',
        ),
    ]
