# Generated by Django 2.1.5 on 2019-08-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0064_auto_20190813_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='defektai',
            field=models.CharField(default='Nothing', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='kebuloTipas',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Station Wagon', 'Station Wagon'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Other', 'Other')], default='Sedan', max_length=25),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='pavaruDeze',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Manual', max_length=25),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='prekyboje',
            field=models.CharField(choices=[('Parduodama', 'Selling'), ('Parduota', 'Sold'), ('Rezervuota', 'Reserved'), ('Kita', 'Other')], default='Parduodama', max_length=10, verbose_name='Prekyboje?'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='varantisRatai',
            field=models.CharField(default='FWD', max_length=100),
        ),
    ]
