# Generated by Django 2.1.5 on 2019-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0065_auto_20190813_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='prekyboje',
            field=models.CharField(choices=[('Selling', 'Selling'), ('Sold', 'Sold'), ('Reserved', 'Reserved'), ('Other', 'Other')], default='Selling', max_length=10, verbose_name='Prekyboje?'),
        ),
    ]
