# Generated by Django 2.1.5 on 2019-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0066_auto_20190813_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='prekyboje',
            field=models.CharField(choices=[('Parduodama', 'Selling'), ('Parduota', 'Sold'), ('Rezervuota', 'Reserved'), ('Kita', 'Other')], default='Parduodama', max_length=10, verbose_name='Prekyboje?'),
        ),
    ]
